#!/bin/bash

rm -rf lpcoolkit

mkdir -p lpctoolkit/lpctoolkit-externals
mkdir -p lpctoolkit/lpctoolkit-help

find ../sdk-build/* -name '*.mxo' -exec cp -r {} ./lpctoolkit/lpctoolkit-externals/. \;
find ../src/* -name '*.maxhelp' -exec cp -r {} ./lpctoolkit/lpctoolkit-help/. \;
cp -r ../src/lpcToolkitDemo.maxpat ./lpctoolkit/lpctoolkit-help/. 
cp README ./lpctoolkit/.

